### ISSUE TITLE
hard coded path

### ISSUE THREAD

**Issue by mcroxen** [BU-ISCIII/plasmidID#2]
It assumes specific directory for trimmomatic install.

lib/quality_trim.sh

trimmomatic_directory=/opt/Trimmomatic/

also a suggestion: to check all dependencies before running, not just before each step.

**Comment by pedroscampoy** [comment]
/opt/Trimmomatic/ is a default parameter that can be modified with -d flag, but, as you noted, is not implemented in plasmidID.sh.

Since Trimmomatic depends on java, its execution is tricky and depends on many parameters.

This will be solved soon, by adding an option to select trimmomatic directory or changing the quality trimming software.

The short term solution is one of the following:
 - Include Trimmomatic folder in /opt
 - Add on line 292: lib/quality_trim.sh -1 $r1_file -2 $r2_file -s $sample -g $group -T $threads -d (TRIMMOMATIC/PATH)
- use --no-trim  flag in plasmidID.sh execution 

I am aware that those solutions aren't elegant and this issue will be addressed soon.

Thank you so much for your contribution!

**Comment by pedroscampoy** [comment]
Regarding to your suggestion, it will also be implemented. It must be frustrating to find out there is a missing dependency after mapping step. 

I will  include your suggestion in next release.

Thank you so much!
