### ISSUE TITLE
Can't create database with multiple threads

### ISSUE THREAD

**Issue by swuyts** [BU-ISCIII/plasmidID#6]
Hi there,

I'd like to give plasmidID a shot! Therefore I was following the instructions provided on the wiki to create a database. Last night, I executed the last step using the following command:

```
cdhit_cluster.sh -i plasmids_term.fasta -p -M 20000 -c 100 -T 16
```
However, while I suspected it to run on our 16 threads, I just noticed that it is actually only using one single thread. The `blastn` commands that are running after executing this script also show the option `-num_threads 1`. 

I'm guessing that clustering of the sequencing can take quite a while on just one single thread, so I'd rather have it run parallel. Any insights on how this could happen?

Thank you!

**Comment by pedroscampoy** [comment]
Hello @swuyts. 

-p option in this script executes psi-cd-hit.pl, a standalone program within cd-hit software specific for huge databases. By the time we were testing multi-thread, only cd-hit and cd-hit-est were supported. 
psi-cd-hit.pl seems to implement parallelization too. It will definitely be addressed in the next release this week, now you can use the command as follow while this issue is solved. 

```
psi-cd-hit.pl -i PATH/TO/FILE/plasmids_term.fasta -o PATH/TO/FILE/plasmids_term_100 -c 1 -n 5 -g 1 -M 20000 -core 16
```
Hope it works.

Thank you for your contribution!

**Comment by swuyts** [comment]
Thank you for your reply!

For some reason this command is just throwing the help message of psi-cd-hit without any further error messages. I'm not sure whether I'm missing any other necessary options or it's just a rogue installation of psi-cd-hit.

Anyways, I'll wait for the update and test that one!

Thank you!
